server:
  port: 8099
# 数据库配置
spring:
  datasource:
    url:  jdbc:mysql:///springboot
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jmx:
    server:
# mybatis配置

